### ISSUE TITLE
does it still work?

### ISSUE THREAD

**Issue by stefangweichinger** [opsxcq/prometheus-exporter-fujitsu#1]
found your project while searching for an exporter for a TX1330M4 IRMC .. I just want to point it at that IRMC and see if something useful is exported

Trying this:

```
cat docker-compose.yml 
version: "3.8"
services:

  exporter:
    image: strm/prometheus-exporter-fujitsu
    environment:
      FUJITSU_URL: 'http://xx.yy.zz.aa:55123'
      FUJITSU_USER: 'admin'
      FUJITSU_PASS: 'xxx'
    networks:
      - proxy

networks:
  proxy:
    external: true
```

only getting:

```
docker-compose up
Starting prometheus-exporter-fujitsu_exporter_1 ... done
Attaching to prometheus-exporter-fujitsu_exporter_1
exporter_1  | 2023/07/06 15:18:56 Initializing metrics on describe
```

any hints or ideas? thanks ...
